/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import Model.Benh;
import Model.BenhNhan;
import Controller.PictureFuzzySet;
import Controller.ChuanDoan;
import Controller.DaiSoGiaTu;
import Dao.BenhDAO;
import Dao.BenhNhanDAO;

/**
 *
 * @author Admin
 */
public class SystemPictureFuzzy extends javax.swing.JFrame {

	private BenhNhan benhNhan ;
	private BenhNhanDAO benhNhanDAO = new BenhNhanDAO();
	private Benh benh;
	private BenhDAO benhDAO = new BenhDAO();
    private String imageInsert;
    private DaiSoGiaTu daiSoGiaTu = new DaiSoGiaTu();
    private ChuanDoan chuanDoan;
    private String nhietDo_x = "";
    private String nhietDo_y = "";
    private String nhietDo_z = "";
    private String dauDau_x = "";
    private String dauDau_y = "";
    private String dauDau_z = "";
    private String dauBung_x = "";
    private String dauBung_y = "";
    private String dauBung_z = "";
    private String ho_x = "";
    private String ho_y = "";
    private String ho_z = "";
    private String dauNguc_x = "";
    private String dauNguc_y = "";
    private String dauNguc_z = "";
    private String name;
    private JFileChooser fc = new JFileChooser();
    private PictureFuzzySet B[][] = new PictureFuzzySet[5][5];
    private String language1 = "English";
    private String errorTimKiem = "Patient data is not available in the system";
    private String errorChanDoan = "You have not selected a patient yet";
    private String errorTrungGian = "You have not run diagnostics yet";
    private String errorSave1 = "The information has been saved";
    private String errorSave2 = "There was an error processing";
    private String errorInsert1 = "Add patient successfully";
    private String errorInsert2 = "ID patient already exists";

    /**
     * Creates new form System
     */
    public SystemPictureFuzzy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */                       
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btgGender = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbDauNguc = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbDauNguc_x = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cbDauNguc_y = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        cbDauNguc_z = new javax.swing.JComboBox<>();
        lbHo = new javax.swing.JLabel();
        cbHo_x = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cbHo_y = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        cbHo_z = new javax.swing.JComboBox<>();
        lbDauBung = new javax.swing.JLabel();
        cbDauBung_x = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbDauBung_y = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cbDauBung_z = new javax.swing.JComboBox<>();
        lbDauDau = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbDauDau_x = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cbDauDau_y = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbDauDau_z = new javax.swing.JComboBox<>();
        lbNhietDo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbNhietDo_x = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbNhietDo_y = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbNhietDo_z = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btChuanDoan = new javax.swing.JButton();
        tfTenBenh = new javax.swing.JTextField();
        btTapTrieuChung = new javax.swing.JButton();
        btBenhNhanBenh = new javax.swing.JButton();
        btXacSuat = new javax.swing.JButton();
        cbLanguage1 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        lbPatient = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();
        btFind = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfNameInsert = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfIDInsert = new javax.swing.JTextField();
        btThem = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfHomeTownInsert = new javax.swing.JTextField();
        tfBirthInsert = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        rdMale = new javax.swing.JRadioButton();
        rdFemale = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btImage = new javax.swing.JButton();
        lbInsertImage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfIdPatientDB = new javax.swing.JTextField();
        btHistory = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        lbImageHistory = new javax.swing.JLabel();
        lbPatientNameHistory = new javax.swing.JLabel();
        lbHomeTownHistory = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chương trình chuẩn đoán bệnh");

        lbDauNguc.setText("Chest pain ");

        jLabel17.setText("Positive");

        cbDauNguc_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
        cbDauNguc_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDauNguc_xActionPerformed(evt);
            }
        });

        jLabel20.setText("Neutral");

        cbDauNguc_y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
        cbDauNguc_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDauNguc_yActionPerformed(evt);
            }
        });

        jLabel23.setText("Negative");

        cbDauNguc_z.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
        cbDauNguc_z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDauNguc_zActionPerformed(evt);
            }
        });

        lbHo.setText("Cough");

        cbHo_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
        cbHo_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHo_xActionPerformed(evt);
            }
        });

        jLabel19.setText("Neutral");

        cbHo_y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
        cbHo_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHo_yActionPerformed(evt);
            }
        });

        jLabel22.setText("Negative");

        cbHo_z.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
        cbHo_z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHo_zActionPerformed(evt);
            }
        });

        lbDauBung.setText("Stomachache");

        cbDauBung_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
        cbDauBung_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDauBung_xActionPerformed(evt);
            }
        });

        jLabel15.setText("Positive");

        jLabel18.setText("Neutral");

        cbDauBung_y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
        cbDauBung_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDauBung_yActionPerformed(evt);
            }
        });

        jLabel21.setText("Negative");

        cbDauBung_z.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
        cbDauBung_z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDauBung_zActionPerformed(evt);
            }
        });

        lbDauDau.setText("Headache");

        jLabel12.setText("Positive");

        cbDauDau_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
        cbDauDau_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDauDau_xActionPerformed(evt);
            }
        });

        jLabel13.setText("Neutral");

        cbDauDau_y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
        cbDauDau_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDauDau_yActionPerformed(evt);
            }
        });

        jLabel14.setText("Negative");

        cbDauDau_z.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
        cbDauDau_z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDauDau_zActionPerformed(evt);
            }
        });

        lbNhietDo.setText("Temperature");

        jLabel5.setText("Positive");

        cbNhietDo_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
        cbNhietDo_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNhietDo_xActionPerformed(evt);
            }
        });

        jLabel6.setText("Neutral");

        cbNhietDo_y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
        cbNhietDo_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNhietDo_yActionPerformed(evt);
            }
        });

        jLabel7.setText("Negative");

        cbNhietDo_z.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
        cbNhietDo_z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNhietDo_zActionPerformed(evt);
            }
        });

        jLabel4.setText("Select the level of symptoms ");

        btChuanDoan.setText("Diagnostic");
        btChuanDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChuanDoanActionPerformed(evt);
            }
        });

        btTapTrieuChung.setText("View symptom episode");
        btTapTrieuChung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTapTrieuChungActionPerformed(evt);
            }
        });

        btBenhNhanBenh.setText("View patient - illness episode");
        btBenhNhanBenh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBenhNhanBenhActionPerformed(evt);
            }
        });

        btXacSuat.setText("View probability of disease");
        btXacSuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXacSuatActionPerformed(evt);
            }
        });

        cbLanguage1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Vietnamese" }));
        cbLanguage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLanguage1ActionPerformed(evt);
            }
        });

        jLabel31.setText("Choose language");

        jLabel32.setText("Positive");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDauDau)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel31))
                            .addComponent(lbDauNguc)
                            .addComponent(lbDauBung))
                        .addGap(18, 18, 18)
                        .addComponent(cbLanguage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btTapTrieuChung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btBenhNhanBenh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btXacSuat))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lbNhietDo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbHo)
                                    .addComponent(btChuanDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbDauDau_x, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDauBung_x, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbHo_x, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDauNguc_x, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbNhietDo_x, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbHo_y, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDauNguc_y, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDauBung_y, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDauDau_y, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbNhietDo_y, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbHo_z, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDauNguc_z, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDauBung_z, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDauDau_z, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbNhietDo_z, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tfTenBenh)))
                    .addComponent(jScrollPane1))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLanguage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNhietDo)
                    .addComponent(jLabel5)
                    .addComponent(cbNhietDo_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbNhietDo_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbNhietDo_z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbDauDau_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cbDauDau_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cbDauDau_z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDauDau))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cbDauBung_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDauBung_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel18)
                    .addComponent(lbDauBung)
                    .addComponent(cbDauBung_z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cbHo_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHo)
                    .addComponent(cbHo_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(cbHo_z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDauNguc)
                            .addComponent(cbDauNguc_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(cbDauNguc_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDauNguc_z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btChuanDoan)
                    .addComponent(tfTenBenh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTapTrieuChung)
                    .addComponent(btBenhNhanBenh)
                    .addComponent(btXacSuat))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbImage.setBackground(new java.awt.Color(255, 255, 255));
        lbImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImage.setText("Choose Image");
        lbImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbPatient.setText("Patient name");

        jLabel2.setText("ID");

        btSave.setText("Save data");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btSaveActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btFind.setText("Find Patient");
        btFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btFindActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfID, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(lbPatient)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btFind, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btFind)
                .addGap(34, 34, 34)
                .addComponent(btSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Medical Diagnosis Program", jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Patient name");

        jLabel8.setText("ID");

        btThem.setText("Insert");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btThemActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jLabel9.setText("Home town");

        jLabel10.setText("Birth");

        jLabel24.setText("Gender");

        btgGender.add(rdMale);
        rdMale.setText("Male");
        rdMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformed(evt);
            }
        });

        btgGender.add(rdFemale);
        rdFemale.setText("Female");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel24)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNameInsert)
                            .addComponent(tfIDInsert)
                            .addComponent(tfHomeTownInsert)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(rdMale)
                                .addGap(75, 75, 75)
                                .addComponent(rdFemale)
                                .addGap(0, 191, Short.MAX_VALUE))
                            .addComponent(tfBirthInsert))
                        .addGap(158, 158, 158))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNameInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfIDInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHomeTownInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfBirthInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(rdMale)
                    .addComponent(rdFemale))
                .addGap(18, 18, 18)
                .addComponent(btThem)
                .addContainerGap())
        );

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Enter patient information ");

        btImage.setText("Choose Image");
        btImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImageActionPerformed(evt);
            }
        });

        lbInsertImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInsertImage.setText("Choose Image");
        lbInsertImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbInsertImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 79, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbInsertImage, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbInsertImage, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(383, 383, 383))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Insert Patient", jPanel3);

        jLabel1.setText("Enter ID Patient");

        btHistory.setText("View History");
        btHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btHistoryActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        lbImageHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImageHistory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbImageHistory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbPatientNameHistory.setText("Patient name");

        lbHomeTownHistory.setText("Home town");

        jLabel27.setText("Birth ");

        jLabel28.setText("Gender");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbHomeTownHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPatientNameHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImageHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel26)
                    .addComponent(jLabel11))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(lbPatientNameHistory))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbImageHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHomeTownHistory)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel30))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Th", "Fever", "Malaria", "Typhoid", "Stomach", "Chest problem"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jScrollPane3.setViewportView(jScrollPane2);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(tfIdPatientDB, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btHistory))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIdPatientDB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHistory))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("View the medical history of the patient", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                      

    private void cbNhietDo_xActionPerformed(java.awt.event.ActionEvent evt) {                                            
        nhietDo_x = (String) cbNhietDo_x.getSelectedItem();
        KiemTraDauVaoY(nhietDo_x, cbNhietDo_y);
    }                                           

    private void cbNhietDo_yActionPerformed(java.awt.event.ActionEvent evt) {                                            
        nhietDo_y = (String) cbNhietDo_y.getSelectedItem();
        KiemTraDauVaoZ(nhietDo_x, nhietDo_y, cbNhietDo_z);
    }                                           

    private void cbNhietDo_zActionPerformed(java.awt.event.ActionEvent evt) {                                            
        nhietDo_z = (String) cbNhietDo_z.getSelectedItem();
    }                                           

    private void cbDauDau_xActionPerformed(java.awt.event.ActionEvent evt) {                                           
        dauDau_x = (String) cbDauDau_x.getSelectedItem();
        KiemTraDauVaoY(dauDau_x, cbDauDau_y);
    }                                          

    private void cbDauDau_yActionPerformed(java.awt.event.ActionEvent evt) {                                           
        dauDau_y = (String) cbDauDau_y.getSelectedItem();
        KiemTraDauVaoZ(dauDau_x, dauDau_y, cbDauDau_z);
    }                                          

    private void cbDauDau_zActionPerformed(java.awt.event.ActionEvent evt) {                                           
        dauDau_z = (String) cbDauDau_z.getSelectedItem();
    }                                          

    private void cbDauBung_xActionPerformed(java.awt.event.ActionEvent evt) {                                            
        dauBung_x = (String) cbDauBung_x.getSelectedItem();
        KiemTraDauVaoY(dauBung_x, cbDauBung_y);
    }                                           

    private void cbDauBung_yActionPerformed(java.awt.event.ActionEvent evt) {                                            
        dauBung_y = (String) cbDauBung_y.getSelectedItem();
        KiemTraDauVaoZ(dauBung_x, dauBung_y, cbDauBung_z);
    }                                           

    private void cbDauBung_zActionPerformed(java.awt.event.ActionEvent evt) {                                            
        dauBung_z = (String) cbDauBung_z.getSelectedItem();
    }                                           

    private void cbHo_xActionPerformed(java.awt.event.ActionEvent evt) {                                       
        ho_x = (String) cbHo_x.getSelectedItem();
        KiemTraDauVaoY(ho_x, cbHo_y);
    }                                      

    private void cbHo_yActionPerformed(java.awt.event.ActionEvent evt) {                                       
        ho_y = (String) cbHo_y.getSelectedItem();
        KiemTraDauVaoZ(ho_x, ho_y, cbHo_z);
    }                                      

    private void cbHo_zActionPerformed(java.awt.event.ActionEvent evt) {                                       
        ho_z = (String) cbHo_z.getSelectedItem();
    }                                      

    private void cbDauNguc_xActionPerformed(java.awt.event.ActionEvent evt) {                                            
        dauNguc_x = (String) cbDauNguc_x.getSelectedItem();
        KiemTraDauVaoY(dauNguc_x, cbDauNguc_y);
    }                                           

    private void cbDauNguc_yActionPerformed(java.awt.event.ActionEvent evt) {                                            
        dauNguc_y = (String) cbDauNguc_y.getSelectedItem();
        KiemTraDauVaoZ(dauNguc_x, dauNguc_y, cbDauNguc_z);
    }                                           

    private void cbDauNguc_zActionPerformed(java.awt.event.ActionEvent evt) {                                            
        dauNguc_z = (String) cbDauNguc_z.getSelectedItem();
    }                                           

    private void btChuanDoanActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	if(benhNhan != null) {
    		setPictureFuzzySet();
            ArrayList benh = new ArrayList<Object>();
            if(language1.equals("English")){
                benh = chuanDoan.ChuanDoanBenh2();
            }else if(language1.equals("Vietnamese")){
                benh = chuanDoan.ChuanDoanBenh();
            }
            
            String dsBenh = "   ";
            for (int i = 0; i < benh.size(); i++) {
                dsBenh = dsBenh.concat((String) benh.get(i));
                dsBenh = dsBenh.concat("    ");

            }
            System.out.println("Tên bệnh : " + dsBenh);
            tfTenBenh.setText(dsBenh);
    	}else {
    		JOptionPane.showMessageDialog(this, errorChanDoan,"Error",JOptionPane.ERROR_MESSAGE);	
    	}
        
    }                                           

    private void btTapTrieuChungActionPerformed(java.awt.event.ActionEvent evt) {                                                
    	
    	if(chuanDoan != null) {
    		String data[][] = new String[1][5];
    		String colums2[] = {BenhNhan.S2[0], BenhNhan.S2[1], BenhNhan.S2[2], BenhNhan.S2[3], BenhNhan.S2[4]};
    		String colums1[] = {BenhNhan.S[0], BenhNhan.S[1], BenhNhan.S[2], BenhNhan.S[3], BenhNhan.S[4]};
            int i = 0;
            for (PictureFuzzySet set : benhNhan.getSet()) {
                data[0][i] = set.toString();
                i++;
            }
            if(language1.equals("English")){
                jTable1.setModel(new javax.swing.table.DefaultTableModel(data, colums2));
            }else if(language1.equals("Vietnamese")){
                jTable1.setModel(new javax.swing.table.DefaultTableModel(data, colums1));
            }  
    	}else {
    		JOptionPane.showMessageDialog(this, errorTrungGian,"Error",JOptionPane.ERROR_MESSAGE);
    	}
        
    }                                               

    private void btBenhNhanBenhActionPerformed(java.awt.event.ActionEvent evt) {                                               
    	if(chuanDoan != null) {
    		String data[][] = new String[1][5];
    		String colums1[] = {ChuanDoan.D[0], ChuanDoan.D[1], ChuanDoan.D[2], ChuanDoan.D[3], ChuanDoan.D[4]};
    		String colums2[] = {ChuanDoan.D2[0], ChuanDoan.D2[1], ChuanDoan.D2[2], ChuanDoan.D2[3], ChuanDoan.D2[4]};
            int i = 0;
            for (PictureFuzzySet set : chuanDoan.getC()) {
                data[0][i] = set.toString();
                i++;
            }
            if (language1.equals("English")) {
                jTable1.setModel(new javax.swing.table.DefaultTableModel(data, colums2));
            } else if (language1.equals("Vietnamese")) {
                jTable1.setModel(new javax.swing.table.DefaultTableModel(data, colums1));
            }
    	}else {
    		JOptionPane.showMessageDialog(this, errorTrungGian,"Error",JOptionPane.ERROR_MESSAGE);
    	}
        

    }                                              

    private void btXacSuatActionPerformed(java.awt.event.ActionEvent evt) {                                          
    	if(chuanDoan != null) {
    		String data[][] = new String[1][5];
    		String colums1[] = {ChuanDoan.D[0], ChuanDoan.D[1], ChuanDoan.D[2], ChuanDoan.D[3], ChuanDoan.D[4]};
    		String colums2[] = {ChuanDoan.D2[0], ChuanDoan.D2[1], ChuanDoan.D2[2], ChuanDoan.D2[3], ChuanDoan.D2[4]};
            for (int i = 0; i < chuanDoan.getX().length; i++) {
                data[0][i] = Double.toString(chuanDoan.getX()[i]);
            }
            if (language1.equals("English")) {  
                jTable1.setModel(new javax.swing.table.DefaultTableModel(data, colums2));
            } else if (language1.equals("Vietnamese")) {
                jTable1.setModel(new javax.swing.table.DefaultTableModel(data, colums1));
            }
    	}else {
    		JOptionPane.showMessageDialog(this, errorTrungGian,"Error",JOptionPane.ERROR_MESSAGE);
    	}
        
    }                                                                                  

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {  
    	benh = new Benh(0, benhNhan.getIdBenhNhan(), chuanDoan.getX()[0], chuanDoan.getX()[1], chuanDoan.getX()[2], chuanDoan.getX()[3], chuanDoan.getX()[4]);
    	if(benhDAO.themTapXacSuatBenh(benh)) {
    		JOptionPane.showMessageDialog(this, errorSave1);
    	}else {
    		JOptionPane.showMessageDialog(this, errorSave2,"Error",JOptionPane.ERROR_MESSAGE);
    	}
    	
    }                                      
                                         

    private void btHistoryActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                          
        int idBenhNhan = Integer.parseInt(tfIdPatientDB.getText());
        ArrayList<Benh> listBenh = benhDAO.LichSuKhamBenh(idBenhNhan);
        BenhNhan b = benhNhanDAO.timKiemBenhNhan(idBenhNhan);
        lbImageHistory.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("../image/"+b.getImage())).getImage().getScaledInstance(156, 156, Image.SCALE_SMOOTH)));
        Double data[][] = new Double[listBenh.size()][6] ;
        String colums2[]= {"Th",ChuanDoan.D2[0],ChuanDoan.D2[1],ChuanDoan.D2[2],ChuanDoan.D2[3],ChuanDoan.D2[4]};
        String colums1[]= {"Lần thứ",ChuanDoan.D[0],ChuanDoan.D[1],ChuanDoan.D[2],ChuanDoan.D[3],ChuanDoan.D[4]};
        int i=0;
        for(Benh benh : listBenh) {
        	double stt = i+1;
        	data[i][0] = stt;
        	data[i][1] = benh.getSotVirut();
        	data[i][2] = benh.getSotRet();
        	data[i][3] = benh.getThuongHan();
        	data[i][4] = benh.getDaDay();
        	data[i][5] = benh.getTim();
        	i++;
        }
        jLabel11.setText(b.getName());
        jLabel26.setText(b.getHomeTown());
        jLabel29.setText(b.getBirth());
        
        if(language1.equals("English")) {
        	if(b.isGender()==true) {
            	jLabel30.setText("Male");
            }else {
            	jLabel30.setText("Female");
            }
        	jTable2.setModel(new javax.swing.table.DefaultTableModel(data,colums2));
        }else if(language1.equals("Vietnamese")) { 
        	if(b.isGender()==true) {
            	jLabel30.setText("nam");
            }else {
            	jLabel30.setText("nữ");
            }
        	jTable2.setModel(new javax.swing.table.DefaultTableModel(data,colums1));
        }
    }                                         

    private void btImageActionPerformed(java.awt.event.ActionEvent evt) {                                        
        int select = fc.showOpenDialog(this);
        if (select == JFileChooser.APPROVE_OPTION) {
            java.io.File file = fc.getSelectedFile();
            try {
                BufferedImage image = ImageIO.read(file);
                ImageIcon icon = new ImageIcon(image.getScaledInstance(156, 156, image.SCALE_SMOOTH));
                System.out.println(file.getName());
                imageInsert = file.getName();
                lbInsertImage.setIcon(icon);
                lbInsertImage.setText("");

            } catch (IOException ex) {
                Logger.getLogger(SystemPictureFuzzy.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            lbInsertImage.setText("Choose image again");
        }
    } 
    
    private void btFindActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                       
    	int idBenhNhan = Integer.parseInt(tfID.getText());
    	if(benhNhanDAO.timKiemBenhNhan(idBenhNhan).getName() == null) {
    		JOptionPane.showMessageDialog(this, errorTimKiem,"Error",JOptionPane.ERROR_MESSAGE);
    	}else {
    		benhNhan = benhNhanDAO.timKiemBenhNhan(idBenhNhan);
    		System.out.println(benhNhan.getImage());
        	String anh = benhNhan.getImage();
        	lbImage.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("../image/"+anh)).getImage().getScaledInstance(156, 156, Image.SCALE_SMOOTH)));
        	lbImage.setText("");
        	jLabel33.setText(benhNhan.getName());
    	}
    }
    
    private void btThemActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                       
        String name = tfNameInsert.getText();
        int idBenhNhan = Integer.parseInt(tfIDInsert.getText());
        String homeTown = tfHomeTownInsert.getText();
        String birth = tfBirthInsert.getText();
        boolean gender = false;
        if(rdMale.isSelected()) {
        	gender = true;
        }
        if(rdFemale.isSelected()) {
        	gender = false;
        }
        BenhNhan b = new BenhNhan(idBenhNhan, name, imageInsert, homeTown, birth, gender);
        
        System.out.println(b.getIdBenhNhan()+"-"+b.getName()+"-"+b.getHomeTown()+"-"+b.getBirth()+"-"+b.isGender());
        if(benhNhanDAO.themBenhNhan(b)) {
        	 JOptionPane.showMessageDialog(this, errorInsert1);
        }else {
        	JOptionPane.showMessageDialog(this, errorInsert2,"Error",JOptionPane.ERROR_MESSAGE);
        }
    } 
    
    private void cbLanguage1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        SetLanguage();
    }                                           

    public void setPictureFuzzySet() {
    	if(benhNhan == null) {
    		JOptionPane.showMessageDialog(this, errorTimKiem);
    	}else {
    		
    		if(language1.equals("English")){
    			benhNhan.InputSet2(nhietDo_x, nhietDo_y, nhietDo_z, 0);
    			benhNhan.InputSet2(dauDau_x, dauDau_y, dauDau_z, 1);
    			benhNhan.InputSet2(dauBung_x, dauBung_y, dauBung_z, 2);
    			benhNhan.InputSet2(ho_x, ho_y, ho_z, 3);
    			benhNhan.InputSet2(dauNguc_x, dauNguc_y, dauNguc_z, 4);
            } 
            if(language1.equals("Vietnamese")){
            	benhNhan.InputSet1(nhietDo_x, nhietDo_y, nhietDo_z, 0);
            	benhNhan.InputSet1(dauDau_x, dauDau_y, dauDau_z, 1);
            	benhNhan.InputSet1(dauBung_x, dauBung_y, dauBung_z, 2);
            	benhNhan.InputSet1(ho_x, ho_y, ho_z, 3);
            	benhNhan.InputSet1(dauNguc_x, dauNguc_y, dauNguc_z, 4);
            }
            InputB(B);
            chuanDoan = new ChuanDoan();
            chuanDoan.QuanHe_BenhNhan_Benh(benhNhan.getSet(), B);
    	}
        
    }

    public void KiemTraDauVaoY(String nhietDo_x, JComboBox cb1) {
        String A[] = new String[9];
        int i = 0;
        TreeMap<Double, String> treeMap = new TreeMap<>();
        if (language1.equals("English")) {
            double x = daiSoGiaTu.getValue2(nhietDo_x);
            for (String key : daiSoGiaTu.getHashMap2().keySet()) {
                if (daiSoGiaTu.getHashMap2().get(key) <= 1.0 - x) {
                    treeMap.put(daiSoGiaTu.getHashMap2().get(key), key);
                }
            }
        }else if(language1.equals("Vietnamese")){
            double x = daiSoGiaTu.getValue(nhietDo_x);
            for (String key : daiSoGiaTu.getHashMap().keySet()) {
                if (daiSoGiaTu.getHashMap().get(key) <= 1.0 - x) {
                    treeMap.put(daiSoGiaTu.getHashMap().get(key), key);
                }
            }
        }

        for (String value : treeMap.values()) {
            A[i++] = value;
        }
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(A));
    }

    public void KiemTraDauVaoZ(String nhietDo_x, String nhietDo_y, JComboBox cb2) {
        String A[] = new String[9];
        int i = 0;
        TreeMap<Double, String> treeMap = new TreeMap<>();
        if (language1.equals("English")) {
            double x = daiSoGiaTu.getValue2(nhietDo_x);
            double y = daiSoGiaTu.getValue2(nhietDo_y);
            for (String key : daiSoGiaTu.getHashMap2().keySet()) {
                if (daiSoGiaTu.getHashMap2().get(key) <= 1.0 - x - y) {
                    treeMap.put(daiSoGiaTu.getHashMap2().get(key), key);
                }
            }
        }else if(language1.equals("Vietnamese")){
            double x = daiSoGiaTu.getValue(nhietDo_x);
            double y = daiSoGiaTu.getValue(nhietDo_y);
            for (String key : daiSoGiaTu.getHashMap().keySet()) {
                if (daiSoGiaTu.getHashMap().get(key) <= 1.0 - x - y) {
                    treeMap.put(daiSoGiaTu.getHashMap().get(key), key);
                }
            }
        }

        for (String value : treeMap.values()) {
            A[i++] = value;
        }
        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(A));
    }

    public static void InputB(PictureFuzzySet A[][]) {
        A[0][0] = new PictureFuzzySet(0.4, 0.4, 0.05);
        A[0][1] = new PictureFuzzySet(0.4, 0.25, 0.3);
        A[0][2] = new PictureFuzzySet(0.1, 0.25, 0.6);
        A[0][3] = new PictureFuzzySet(0.45, 0.2, 0.1);
        A[0][4] = new PictureFuzzySet(0.05, 0.25, 0.6);
        A[1][0] = new PictureFuzzySet(0.8, 0.1, 0.1);
        A[1][1] = new PictureFuzzySet(0.1, 0.2, 0.6);
        A[1][2] = new PictureFuzzySet(0.01, 0.03, 0.9);
        A[1][3] = new PictureFuzzySet(0.65, 0.5, 0.05);
        A[1][4] = new PictureFuzzySet(0.03, 0.07, 0.8);
        A[2][0] = new PictureFuzzySet(0.3, 0.3, 0.3);
        A[2][1] = new PictureFuzzySet(0.75, 0.05, 0.03);
        A[2][2] = new PictureFuzzySet(0.1, 0.2, 0.7);
        A[2][3] = new PictureFuzzySet(0.2, 0.15, 0.6);
        A[2][4] = new PictureFuzzySet(0.01, 0.01, 0.85);
        A[3][0] = new PictureFuzzySet(0.15, 0.05, 0.6);
        A[3][1] = new PictureFuzzySet(0.3, 0.05, 0.05);
        A[3][2] = new PictureFuzzySet(0.8, 0.1, 0.01);
        A[3][3] = new PictureFuzzySet(0.25, 0.25, 0.5);
        A[3][4] = new PictureFuzzySet(0.1, 0.1, 0.7);
        A[4][0] = new PictureFuzzySet(0.05, 0.15, 0.7);
        A[4][1] = new PictureFuzzySet(0.01, 0.1, 0.8);
        A[4][2] = new PictureFuzzySet(0.1, 0.15, 0.75);
        A[4][3] = new PictureFuzzySet(0.15, 0.2, 0.7);
        A[4][4] = new PictureFuzzySet(0.9, 0.02, 0.05);
    }
    
    public void SetLanguage() {
        language1 = (String) cbLanguage1.getSelectedItem();
        if (language1.equals("English")) {
        	setTitle("Diagnosis program");
            jLabel31.setText("choose language");
            jLabel4.setText("Select the level of symptoms");
            lbNhietDo.setText("temperature");
            lbDauDau.setText("headache");
            lbDauBung.setText("stomachache");
            lbHo.setText("cough");
            lbDauNguc.setText("chest pain");
            jLabel5.setText("Positive");
            jLabel6.setText("Neutral");
            jLabel7.setText("Negative");
            jLabel12.setText("Positive");
            jLabel13.setText("Neutral");
            jLabel14.setText("Negative");
            jLabel15.setText("Positive");
            jLabel18.setText("Neutral");
            jLabel21.setText("Negative");
            jLabel32.setText("Positive");
            jLabel19.setText("Neutral");
            jLabel22.setText("Negative");
            jLabel17.setText("Positive");
            jLabel20.setText("Neutral");
            jLabel23.setText("Negative");
            btChuanDoan.setText("Diagnostic");
            btTapTrieuChung.setText("View symptom episode");
            btBenhNhanBenh.setText("View patient - illness episode");
            btXacSuat.setText("View probability of disease");
            lbPatient.setText("Patient name");
            jLabel2.setText("ID");
            btFind.setText("Find Patient");
            btSave.setText("Save data");
            jLabel4.setText("Select the level of symptoms");
            jLabel25.setText("Enter patient information");
            jLabel3.setText("Patient name");
            jLabel8.setText("ID");
            jLabel9.setText("Home town");
            jLabel10.setText("Birth");
            jLabel24.setText("Gender");
            btThem.setText("Insert");
            btImage.setText("Choose Image");
            jLabel1.setText("Enter ID patient");
            btHistory.setText("View history");
            lbPatientNameHistory.setText("Patient name :");
            lbHomeTownHistory.setText("Home town :");
            jLabel27.setText("Birth :");
            jLabel28.setText("Gender :");
            rdMale.setText("Male");
            rdFemale.setText("Female");
            lbInsertImage.setText("Choose Image");
            lbImage.setText("Choose Image");
            errorChanDoan = "You have not selected a patient yet";
            errorTimKiem = "Patient data is not available in the system";
            errorTrungGian = "You have not run diagnostics yet";
            errorSave1 = "The information has been saved";
            errorSave2 = "There was an error processing";
            errorInsert1 = "Add patient successfully";
            errorInsert2 = "ID patient already exists";
            cbDauNguc_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
            cbDauNguc_y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
            cbDauNguc_z.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
            cbNhietDo_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
            cbNhietDo_y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
            cbNhietDo_z.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
            cbDauDau_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
            cbDauDau_y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
            cbDauDau_z.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
            cbDauBung_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
            cbDauBung_y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
            cbDauBung_z.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
            cbHo_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
            cbHo_y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
            cbHo_z.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "very low", "low", "little low", "medium", "little high", "high", "very high", "completely" }));
            
            
        }else if(language1.equals("Vietnamese")){
        	setTitle("Chương trình chuẩn đoán bệnh");
            jLabel31.setText("Chọn ngôn ngữ");
            jLabel4.setText("Chọn các mức độ của triệu chứng");
            lbNhietDo.setText("Nhiệt độ");
            lbDauDau.setText("Đau đầu");
            lbDauBung.setText("Đau bụng");
            lbHo.setText("Ho");
            lbDauNguc.setText("Đau ngực");
            jLabel5.setText("Độ tích cực");
            jLabel6.setText("Độ trung lập");
            jLabel7.setText("Độ phủ định");
            jLabel12.setText("Độ tích cực");
            jLabel13.setText("Độ trung lập");
            jLabel14.setText("Độ phủ định");
            jLabel15.setText("Độ tích cực");
            jLabel18.setText("Độ trung lập");
            jLabel21.setText("Độ phủ định");
            jLabel32.setText("Độ tích cực");
            jLabel19.setText("Độ trung lập");
            jLabel22.setText("Độ phủ định");
            jLabel17.setText("Độ tích cực");
            jLabel20.setText("Độ trung lập");
            jLabel23.setText("Độ phủ định");
            btChuanDoan.setText("Chẩn đoán");
            btTapTrieuChung.setText("Xem tập triệu chứng");
            btBenhNhanBenh.setText("Xem tập bệnh nhân - bệnh");
            btXacSuat.setText("Xem tập xác suất bệnh");
            lbPatient.setText("Tên bệnh nhân");
            jLabel2.setText("Mã số");
            btFind.setText("Tìm bệnh nhân");
            btSave.setText("Lưu dữ liệu");
            jLabel25.setText("Nhập thông tin bệnh nhân");
            jLabel3.setText("Tên bệnh nhân");
            jLabel8.setText("Mã số");
            jLabel9.setText("Quê quán");
            jLabel10.setText("Ngày sinh");
            jLabel24.setText("Giới tính");
            btThem.setText("Thêm");
            btImage.setText("Chọn ản");
            jLabel1.setText("Nhập mã số bệnh nhân");
            btHistory.setText("Xem lịch sử");
            lbPatientNameHistory.setText("Tên bệnh nhân :");
            lbHomeTownHistory.setText("Quê quán :");
            jLabel27.setText("Ngày sinh :");
            jLabel28.setText("Giới tính :");
            rdMale.setText("Nam");
            rdFemale.setText("Nữ");
            lbInsertImage.setText("Chọn ảnh");
            lbImage.setText("Chọn ảnh");
            errorChanDoan = "Bạn chưa chọn bệnh nhân";
            errorTimKiem = "Dữ liệu bệnh nhân không có sẵn trong hệ thống";
            errorTrungGian = "Bạn chưa chạy chẩn đoán";
            errorSave1 = "Thông tin đã được lưu";
            errorSave2 = "có lỗi trong quá trình xử lý";
            errorInsert1 = "Thêm bệnh nhân thành công";
            errorInsert2 = "Mã số bệnh nhân đã tồn tại";
            cbDauNguc_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "khong", "rat thap", "thap", "hoi thap", "trung binh", "hoi cao", "cao", "rat cao", "hoan toan" }));
            cbDauNguc_y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "khong", "rat thap", "thap", "hoi thap", "trung binh", "hoi cao", "cao", "rat cao", "hoan toan" }));
            cbDauNguc_z.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "khong", "rat thap", "thap", "hoi thap", "trung binh", "hoi cao", "cao", "rat cao", "hoan toan" }));
            cbNhietDo_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "khong", "rat thap", "thap", "hoi thap", "trung binh", "hoi cao", "cao", "rat cao", "hoan toan" }));
            cbNhietDo_y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "khong", "rat thap", "thap", "hoi thap", "trung binh", "hoi cao", "cao", "rat cao", "hoan toan" }));
            cbNhietDo_z.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "khong", "rat thap", "thap", "hoi thap", "trung binh", "hoi cao", "cao", "rat cao", "hoan toan" }));
            cbDauDau_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "khong", "rat thap", "thap", "hoi thap", "trung binh", "hoi cao", "cao", "rat cao", "hoan toan" }));
            cbDauDau_y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "khong", "rat thap", "thap", "hoi thap", "trung binh", "hoi cao", "cao", "rat cao", "hoan toan" }));
            cbDauDau_z.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "khong", "rat thap", "thap", "hoi thap", "trung binh", "hoi cao", "cao", "rat cao", "hoan toan" }));
            cbDauBung_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "khong", "rat thap", "thap", "hoi thap", "trung binh", "hoi cao", "cao", "rat cao", "hoan toan" }));
            cbDauBung_y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "khong", "rat thap", "thap", "hoi thap", "trung binh", "hoi cao", "cao", "rat cao", "hoan toan" }));
            cbDauBung_z.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "khong", "rat thap", "thap", "hoi thap", "trung binh", "hoi cao", "cao", "rat cao", "hoan toan" }));
            cbHo_x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "khong", "rat thap", "thap", "hoi thap", "trung binh", "hoi cao", "cao", "rat cao", "hoan toan" }));
            cbHo_y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "khong", "rat thap", "thap", "hoi thap", "trung binh", "hoi cao", "cao", "rat cao", "hoan toan" }));
            cbHo_z.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "khong", "rat thap", "thap", "hoi thap", "trung binh", "hoi cao", "cao", "rat cao", "hoan toan" }));
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemPictureFuzzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemPictureFuzzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemPictureFuzzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemPictureFuzzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemPictureFuzzy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btBenhNhanBenh;
    private javax.swing.JButton btChuanDoan;
    private javax.swing.JButton btFind;
    private javax.swing.JButton btHistory;
    private javax.swing.JButton btImage;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btTapTrieuChung;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXacSuat;
    private javax.swing.ButtonGroup btgGender;
    private javax.swing.JComboBox<String> cbDauBung_x;
    private javax.swing.JComboBox<String> cbDauBung_y;
    private javax.swing.JComboBox<String> cbDauBung_z;
    private javax.swing.JComboBox<String> cbDauDau_x;
    private javax.swing.JComboBox<String> cbDauDau_y;
    private javax.swing.JComboBox<String> cbDauDau_z;
    private javax.swing.JComboBox<String> cbDauNguc_x;
    private javax.swing.JComboBox<String> cbDauNguc_y;
    private javax.swing.JComboBox<String> cbDauNguc_z;
    private javax.swing.JComboBox<String> cbHo_x;
    private javax.swing.JComboBox<String> cbHo_y;
    private javax.swing.JComboBox<String> cbHo_z;
    private javax.swing.JComboBox<String> cbLanguage1;
    private javax.swing.JComboBox<String> cbNhietDo_x;
    private javax.swing.JComboBox<String> cbNhietDo_y;
    private javax.swing.JComboBox<String> cbNhietDo_z;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbDauBung;
    private javax.swing.JLabel lbDauDau;
    private javax.swing.JLabel lbDauNguc;
    private javax.swing.JLabel lbHo;
    private javax.swing.JLabel lbHomeTownHistory;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbImageHistory;
    private javax.swing.JLabel lbInsertImage;
    private javax.swing.JLabel lbNhietDo;
    private javax.swing.JLabel lbPatient;
    private javax.swing.JLabel lbPatientNameHistory;
    private javax.swing.JRadioButton rdFemale;
    private javax.swing.JRadioButton rdMale;
    private javax.swing.JTextField tfBirthInsert;
    private javax.swing.JTextField tfHomeTownInsert;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfIDInsert;
    private javax.swing.JTextField tfIdPatientDB;
    private javax.swing.JTextField tfNameInsert;
    private javax.swing.JTextField tfTenBenh;
    // End of variables declaration                   
}
